ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "termsAcceptedAt"   TIMESTAMP(3);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "termsVersion"      TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "privacyAcceptedAt" TIMESTAMP(3);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "privacyVersion"    TEXT;
