package com.luxgrimoire.backend.controller;

import com.luxgrimoire.backend.model.BookEntry;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController
@RequestMapping("/api/collection")
@CrossOrigin(origins = "http://localhost:5173")
public class BookCollectionController {

    private static final List<BookEntry> BOOKS = List.of(
        new BookEntry("angielski","M. K. Lobb","Seven Faceless Saints","Seven Faceless Saints","1","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Lana Ferguson","The Fake Mate","","","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","S. Jae-Jones","Zhara","Guardians of Dawn","1","Illumicrate","Signature",false,true,""),
        new BookEntry("angielski","Laura Purcell","Moonstone","","","The Locked Library","",false,false,""),
        new BookEntry("angielski","Sunyi Dean","The Book Eaters","","","Illumicrate","Signature",false,false,""),
        new BookEntry("angielski","Jeaniene O'Riley","How Does It Feel","Infatuated Fae","1","The Bookish Box","Signature",false,false,""),
        new BookEntry("angielski","Jeaniene O'Riley","How Does It Feel","Infatuated Fae","1","The Arcane Society","",false,false,""),
        new BookEntry("angielski","Jeaniene O'Riley","What Did You Do?","Infatuated Fae","2","The Arcane Society","",false,false,""),
        new BookEntry("angielski","Kika Hatzopoulou","Hearts That Cut","Threads That Bind","2","OwlCrate","Signature, Bonus content",false,false,""),
        new BookEntry("angielski","Tessonja Odette","A Rivalry Of Hearts","Fae Flings and Corset Strings","1","The Butterfly Book Club","signed bookplate",false,false,""),
        new BookEntry("angielski","Fay Bec","Hidden Beneath The Embers","The Dark Curse","1","The Butterfly Book Club","signed bookplate",false,false,""),
        new BookEntry("angielski","M. Robinson","Second Chance Contract","Second Chance","1","Romance Cartel","signed bookplate",false,true,""),
        new BookEntry("angielski","C. A. Rene, R. E. Bond","The Reaper Incarnate","Reaped","1.5","Romance Cartel","signed bookplate",true,true,""),
        new BookEntry("angielski","Sophie Jordan","A Fire in The Sky","A Fire in the Sky","1","FairyLoot","Signature",true,true,""),
        new BookEntry("angielski","Sylvie Cathrall","A Letter to the Luminous Deep","The Sunken Archive","1","FairyLoot","Signature",true,true,""),
        new BookEntry("angielski","Carissa Broadbent","Six Scorched Roses","Crowns of Nyaxia","1.5","OwlCrate","Signature",false,false,""),
        new BookEntry("angielski","Carissa Broadbent","The Songbird and the Heart of Stone","Crowns of Nyaxia","3","OwlCrate","Signature",false,false,""),
        new BookEntry("angielski","Rebecca F. Garcia","Night of Death and Flowers","Gods of Dahryst Duet","1","Aurora Crate Book Box","signed bookplate",false,false,""),
        new BookEntry("angielski","Judy I. Lin","Song of the Six Realms","","","OwlCrate","Signature, Bonus content",false,true,""),
        new BookEntry("angielski","Morgan Dante","King of Hell","","","Fae Crate","signed bookplate",false,false,""),
        new BookEntry("angielski","Emilia Jae","The Dagger and the Forbidden Heir","The Forbidden Heir Trilogy","1","The Butterfly Book Club","signed bookplate",false,false,""),
        new BookEntry("angielski","Whitney Dean","Rise of the Cinder Fae","Dark Hearts Fairytale Retellings","1","The Butterfly Book Club","signed bookplate",false,false,""),
        new BookEntry("angielski","Mariah Montoya","By the Orchid and the Owl","The Esholian Institute","1","The Butterfly Book Club","signed bookplate",false,false,""),
        new BookEntry("angielski","Jus Accardo","Omen of Ice","Omen of Ice","1","OwlCrate","Signature",false,false,""),
        new BookEntry("angielski","Lyra Selene","A Feather So Black","Fair Folk","1","FairyLoot","Digital signature, Bonus content",true,false,""),
        new BookEntry("angielski","Kathryn Purdie","The Forest Grimm","The Forest Grimm","1","FairyLoot","Digital signature, Bonus content",true,false,""),
        new BookEntry("angielski","Aurora Grey","House of Gilded Nightmares","Dark Fae Guardian","1","Fabled Co","Signature",true,true,""),
        new BookEntry("angielski","Kerri Maniscalco","Throne of the Fallen","Prince of Sin","1","FairyLoot","Digital signature",true,false,""),
        new BookEntry("angielski","O. O. Sangoyomi","Masquerade","","","Fae Crate","Signature",false,true,""),
        new BookEntry("angielski","Ava Reid","Lady Macbeth","","","OwlCrate","Signature, Bonus content",false,false,""),
        new BookEntry("angielski","Kika Hatzopoulou","Threads That Bind","Threads That Bind","1","OwlCrate","Signature, Bonus content",true,false,""),
        new BookEntry("angielski","Carissa Broadbent","The Serpent and the Wings of Night","Crowns of Nyaxia","1","OwlCrate","Digital signature",true,false,""),
        new BookEntry("angielski","Kendare Blake","Anna Dressed In Blood","Anna","1","OwlCrate","Signature, Bonus content",true,false,""),
        new BookEntry("angielski","Caitlin Rozakis","Dreadful","","","The Broken Binding","Signature, numbered",true,true,""),
        new BookEntry("angielski","Elise Kova","A Deal With the Elf King","Married to Magic","1","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Elise Kova","A Dance With the Fae Prince","Married to Magic","2","FairyLoot","",false,false,""),
        new BookEntry("angielski","Elise Kova","A Duel With the Vampire Lord","Married to Magic","3","FairyLoot","",false,false,""),
        new BookEntry("angielski","Carley Spade","Of Magic and Rum","","","Fabled Co","Signature",false,false,""),
        new BookEntry("angielski","A. J. Vrana","Wildblood","","","Fabled Co","Signature",true,true,""),
        new BookEntry("angielski","Holly Black","The Cruel Prince","The Folk of the Air","1","FairyLoot","Digital signature",true,false,""),
        new BookEntry("angielski","Holly Black","The Wicked King","The Folk of the Air","2","FairyLoot","Digital signature",true,false,""),
        new BookEntry("angielski","Holly Black","The Queen of Nothing","The Folk of the Air","3","FairyLoot","Digital signature",true,false,""),
        new BookEntry("angielski","Holly Black","How The King of Elfhame Learned to Hate Stories","The Folk of the Air","3.5","FairyLoot","Digital signature",true,false,""),
        new BookEntry("angielski","Holly Renee","The Veiled Kingdom","The Veiled Kingdom","1","The Bookish Box","Signature, Annotated",false,false,""),
        new BookEntry("angielski","Holly Black","The Stolen Heir","The Stolen Heir Duology","1","FairyLoot","author letter",false,false,""),
        new BookEntry("angielski","Holly Black","The Prisoner's Throne","The Stolen Heir Duology","2","FairyLoot","author letter",false,false,""),
        new BookEntry("angielski","A. N. Caudle","Worthy of Fate","Realms in Peril","1","Fabled Co","Signature",false,false,""),
        new BookEntry("angielski","A. N. Caudle","Worthy of Fate","Realms in Peril","1","Moonlight Book Box","Signature",false,false,""),
        new BookEntry("angielski","Richelle Mead","Vampire Academy","Vampire Academy","1","LitJoy Crate","Signature, Digital signature, Annotated",true,false,""),
        new BookEntry("angielski","Richelle Mead","Frostbite","Vampire Academy","2","LitJoy Crate","Digital signature, Annotated",true,false,""),
        new BookEntry("angielski","Richelle Mead","Shadow Kiss","Vampire Academy","3","LitJoy Crate","Digital signature, Annotated",true,false,""),
        new BookEntry("angielski","Richelle Mead","Blood Promise","Vampire Academy","4","LitJoy Crate","Digital signature, Annotated",true,false,""),
        new BookEntry("angielski","Richelle Mead","Spirit Bound","Vampire Academy","5","LitJoy Crate","Digital signature, Annotated",true,false,""),
        new BookEntry("angielski","Richelle Mead","Last Sacrifice","Vampire Academy","6","LitJoy Crate","Digital signature, Annotated",true,false,""),
        new BookEntry("angielski","Richelle Mead","Vampire Academy","Vampire Academy","1","FairyLoot","Signature",true,false,""),
        new BookEntry("angielski","Richelle Mead","Frostbite","Vampire Academy","2","FairyLoot","",true,false,""),
        new BookEntry("angielski","Richelle Mead","Shadow Kiss","Vampire Academy","3","FairyLoot","",true,false,""),
        new BookEntry("angielski","Richelle Mead","Blood Promise","Vampire Academy","4","FairyLoot","",true,false,""),
        new BookEntry("angielski","Richelle Mead","Spirit Bound","Vampire Academy","5","FairyLoot","",true,false,""),
        new BookEntry("angielski","Richelle Mead","Last Sacrifice","Vampire Academy","6","FairyLoot","",true,false,""),
        new BookEntry("angielski","Holly Renee","A Kingdom of Stars and Shadows","Stars and Shadows","1","Midnight Whispers","signed bookplate",true,false,""),
        new BookEntry("angielski","Holly Renee","A Kingdom of Blood and Betrayal","Stars and Shadows","2","Midnight Whispers","",true,false,""),
        new BookEntry("angielski","Holly Renee","A Kingdom of Venom and Vows","Stars and Shadows","3","Midnight Whispers","",true,false,""),
        new BookEntry("angielski","K. F. Breene","A Ruin of Roses","Deliciously Dark Fairytales","1","Fabled Co","Signature",true,false,""),
        new BookEntry("angielski","K. F. Breene","A Throne of Ruin","Deliciously Dark Fairytales","2","Fabled Co","",true,false,""),
        new BookEntry("angielski","K. F. Breene","A Kingdom of Ruin","Deliciously Dark Fairytales","3","Fabled Co","",true,false,""),
        new BookEntry("angielski","K. F. Breene","A Queen of Ruin","Deliciously Dark Fairytales","4","Fabled Co","",true,false,""),
        new BookEntry("angielski","Leigh Bardugo","Shadow and Bone","Shadow and Bone","1","LitJoy Crate","Annotated, Digital signature",true,false,""),
        new BookEntry("angielski","Leigh Bardugo","Siege and Storm","Shadow and Bone","2","LitJoy Crate","Digital signature",true,false,""),
        new BookEntry("angielski","Leigh Bardugo","Ruin and Rising","Shadow and Bone","3","LitJoy Crate","Digital signature",true,false,""),
        new BookEntry("angielski","Moonlight Muse","Her Forbidden Alpha","Alpha","1","The Butterfly Book Club","Signature",true,false,""),
        new BookEntry("angielski","Shelly Parker-Chan","She Who Became The Sun","The Radiant Emperor","1","The Broken Binding","Signature",true,false,""),
        new BookEntry("angielski","Shelly Parker-Chan","He Who Drowned The World","The Radiant Emperor","2","The Broken Binding","Signature",false,false,""),
        new BookEntry("angielski","Miranda Lyn","The Unmarked Witch","Unmarked","1","Moonlight Book Box","Signature",true,false,""),
        new BookEntry("angielski","Elizabeth Helen","Bonded by Thorns","Beasts of Briar","1","FairyLoot","Signature",true,false,""),
        new BookEntry("angielski","Elizabeth Helen","Bonded by Thorns","Beasts of Briar","1","The Bookish Box","Signature",false,false,""),
        new BookEntry("angielski","Olivia Wildenstein","House of Beating Wings","The Kingdom of Crows","1","Page & Wick","Signature",false,true,""),
        new BookEntry("angielski","Kate Chenli","A Bright Heart","A Bright Heart","1","Fae Crate","signed bookplate",true,true,""),
        new BookEntry("angielski","Sam Mariano","Brutal Ambition","","","Fabled Co","Signature",false,true,""),
        new BookEntry("angielski","Simone St. James","Murder Road","","","Illumicrate","Signature",false,true,""),
        new BookEntry("angielski","Vanessa Le","The Last Bloodcarver","The Last Bloodcarver","","OwlCrate","Signature, Bonus content",true,true,""),
        new BookEntry("angielski","Etta Easton","The Kiss Countdown","","","Illumicrate","Signature",false,true,""),
        new BookEntry("angielski","K. T. Hoffman","The Prospects","","","Illumicrate","Signature",false,true,""),
        new BookEntry("angielski","Sylvia Mercedes","Bride of the Shadow King","Bride of the Shadow King","1","Illumicrate","Signature",true,false,""),
        new BookEntry("angielski","Sylvia Mercedes","Vow of the Shadow King","Bride of the Shadow King","2","Illumicrate","",true,false,""),
        new BookEntry("angielski","Sylvia Mercedes","Heart of the Shadow King","Bride of the Shadow King","3","Illumicrate","",true,false,""),
        new BookEntry("angielski","Danielle L. Jensen","The Bridge Kingdom","The Bridge Kingdom","1","FairyLoot","Signature, Bonus content",true,false,""),
        new BookEntry("angielski","Danielle L. Jensen","The Traitor Queen","The Bridge Kingdom","2","FairyLoot","Signature",true,false,""),
        new BookEntry("angielski","Danielle L. Jensen","The Bridge Kingdom","The Bridge Kingdom","1","The Arcane Society","Signature",true,false,""),
        new BookEntry("angielski","Danielle L. Jensen","The Traitor Queen","The Bridge Kingdom","2","The Arcane Society","Signature",true,false,""),
        new BookEntry("angielski","Danielle L. Jensen","The Inadequate Heir","The Bridge Kingdom","3","The Arcane Society","Signature",false,false,""),
        new BookEntry("angielski","Danielle L. Jensen","The Endless War","The Bridge Kingdom","4","The Arcane Society","Signature",false,false,""),
        new BookEntry("angielski","Sarah A. Parker","When the Moon Hatched","Moonfall","1","The Locked Library","Digital signature",true,false,""),
        new BookEntry("angielski","Sarah A. Parker","When the Moon Hatched","Moonfall","1","FairyLoot","Signature",true,false,""),
        new BookEntry("angielski","Sarah A. Parker","When the Moon Hatched","Moonfall","1","Page & Wick","Signature",true,false,""),
        new BookEntry("angielski","K. A. Linde","The Wren in the Holly Library","The Oak and Holly Cycle","1","FairyLoot","Signature",true,false,""),
        new BookEntry("angielski","K. A. Linde","The Robin on the Oak Throne","The Oak and Holly Cycle","2","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Carissa Broadbent","The Serpent and the Wings of Night","Crowns of Nyaxia","1","FairyLoot","Signature",true,false,""),
        new BookEntry("angielski","Rebecca Yarros","Fourth Wing","The Empyrean","1","FairyLoot","",true,false,""),
        new BookEntry("angielski","Rebecca Yarros","Iron Flame","The Empyrean","2","FairyLoot","",true,false,""),
        new BookEntry("angielski","Trudi Canavan","The Magicians' Guild","The Black Magician","1","Illumicrate","Digital signature",true,false,""),
        new BookEntry("angielski","Trudi Canavan","The Novice","The Black Magician","2","Illumicrate","Digital signature",true,false,""),
        new BookEntry("angielski","Trudi Canavan","The High Lord","The Black Magician","3","Illumicrate","Digital signature",true,false,""),
        new BookEntry("angielski","Emma Cole","Silverlight Heir","Dominion Series","1","Romance Cartel","",true,true,""),
        new BookEntry("angielski","Sasha Peyton Smith","The Rose Bargain","","","FairyLoot","Digital signature",true,true,""),
        new BookEntry("angielski","D. M. Simmons","Legion of the Queen","After the Fall","1","The Butterfly Book Club","Digital signature",true,true,""),
        new BookEntry("angielski","D. M. Simmons","Fealty of the Fallen","After the Fall","2","The Butterfly Book Club","Digital signature",true,true,""),
        new BookEntry("angielski","Adaline Winters","Ruthless Creatures: Beneath Your Beautiful","","","The Butterfly Book Club","Signature",true,true,""),
        new BookEntry("angielski","Travis Baldree","Bookshops & Bonedust","Legends & Lattes","0","The Bookish Box","Signature",true,true,""),
        new BookEntry("angielski","Kika Hatzopoulou","Threads That Bind","Threads That Bind","1","FairyLoot","Signature",true,true,""),
        new BookEntry("angielski","Olivie Blake","Masters of Death","","","OwlCrate","Digital signature",true,true,""),
        new BookEntry("angielski","Olivie Blake","The Atlas Complex","The Atlas","3","FairyLoot","Signature",false,true,""),
        new BookEntry("angielski","Megan Scott","The Temptation of Magic","Empyreal","1","LitJoy Crate","Signature",false,false,""),
        new BookEntry("angielski","Emily Varga","For She Is Wrath","","","OwlCrate","Signature, Bonus content",false,true,""),
        new BookEntry("angielski","Kristen Ciccarelli","Heartless Hunter","The Crimson Moth","1","OwlCrate","Signature, Bonus content",true,false,""),
        new BookEntry("angielski","Julie Leong","The Teller of Small Fortunes","","","OwlCrate","Signature",false,true,""),
        new BookEntry("angielski","T. Kingfisher","A Sorceress Comes to Call","","","Page & Wick","Digital signature",true,true,""),
        new BookEntry("angielski","Harper L. Woods","The Coven","The Coven of Bones","1","Fae Crate","Digital signature",false,false,""),
        new BookEntry("angielski","Beka Westrup","Demons & Roses","The Eternal Brides","1","The Butterfly Book Club","signed bookplate",false,true,""),
        new BookEntry("angielski","Kell Woods","After The Forest","After the Forest","1","OwlCrate","Signature, Bonus content",false,false,""),
        new BookEntry("angielski","Adrienne Young","The Unmaking of June Farrow","","","OwlCrate","Signature, Bonus content",false,false,""),
        new BookEntry("angielski","Adrienne Young","Fallen City","Fallen City Duology","1","FairyLoot","author letter, Bonus content",false,false,""),
        new BookEntry("angielski","Adrienne Young","Fallen City","Fallen City Duology","1","The Bookish Box","Digital signature",false,false,""),
        new BookEntry("angielski","Allison Saft","A Fragile Enchantment","","","OwlCrate","Signature, Bonus content",false,false,""),
        new BookEntry("angielski","Amber Chen","Of Jade and Dragons","Fall of the Dragon","1","OwlCrate","Signature, Bonus content",false,true,""),
        new BookEntry("angielski","K. X. Song","The Night Ends with Fire","The Night Ends with Fire","1","Goldsboro Books","Signature, numbered",false,true,""),
        new BookEntry("angielski","S. T. Gibson","Evocation","The Summoner's Circle","1","OwlCrate","Digital signature, Bonus content",true,true,""),
        new BookEntry("angielski","Isabel Ibanez","What the River Knows","Secrets of the Nile","","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","Isabel Ibanez","Graceless Heart","The Spellbound History","1","FairyLoot","author letter, Bonus content",false,false,""),
        new BookEntry("angielski","Isabel Ibanez","Graceless Heart","The Spellbound History","1","OwlCrate","author letter, Bonus content, Digital signature",false,false,""),
        new BookEntry("angielski","S. M. Gaither","Flame & Sparrow","Flame and Sparrow","1","Page & Wick","Signature",true,true,""),
        new BookEntry("angielski","Alexis L. Menard","House of Bane and Blood","Order and Chaos","1","Fabled Co","Signature",true,true,""),
        new BookEntry("angielski","Vanessa Rasanen","Until the Stars Fall","Immortal Reveries","1","Fae Crate","Signature",false,true,""),
        new BookEntry("angielski","Chloe C. Penaranda","The Stars are Dying","Nytefall","1","OwlCrate","Signature",false,false,""),
        new BookEntry("angielski","Chloe C. Penaranda","The Night is Defying","Nytefall","2","OwlCrate","Signature",false,false,""),
        new BookEntry("angielski","Chloe C. Penaranda","The Dark is Descending","Nytefall","3","OwlCrate","Signature, author letter, Bonus content",false,false,""),
        new BookEntry("angielski","Frances White","Voyage of the Damned","","","Illumicrate","Signature",false,true,""),
        new BookEntry("angielski","Isabel Ibanez","What the River Knows","Secrets of the Nile","1","FairyLoot","Digital signature, Bonus content",false,true,""),
        new BookEntry("angielski","Marianne Gordon","The Gilded Crown","Marianne Gordon","1","The Locked Library","Digital signature",false,false,""),
        new BookEntry("angielski","Kylie Lee Baker","The Scarlet Alchemist","The Scarlet Alchemist","1","FairyLoot","Digital signature",true,true,""),
        new BookEntry("angielski","Devin Madson","Between Dragons and their Wrath","The Shattered Kingdom","1","The Broken Binding","Signature, numbered",false,false,""),
        new BookEntry("angielski","Claire Legrand","Furyborn","The Empirium","1","Illumicrate","Signature",false,false,""),
        new BookEntry("angielski","Claire Legrand","Kingsbane","The Empirium","2","Illumicrate","Digital signature",false,false,""),
        new BookEntry("angielski","Claire Legrand","Lightbringer","The Empirium","3","Illumicrate","Digital signature",false,false,""),
        new BookEntry("angielski","Thilde Kold Holdt","Northern Wrath","Hanged God","1","The Broken Binding","",false,false,""),
        new BookEntry("angielski","Thilde Kold Holdt","Shackled Fates","Hanged God","2","","",false,false,""),
        new BookEntry("angielski","Thilde Kold Holdt","Slaughtered Gods","Hanged God","3","","",false,false,""),
        new BookEntry("angielski","K. J. Sutton","Fortuna Sworn","Fortuna Sworn","1","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","K. J. Sutton","Restless Slumber","Fortuna Sworn","2","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","K. J. Sutton","Deadly Dreams","Fortuna Sworn","3","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","K. J. Sutton","Beautiful Nightmares","Fortuna Sworn","4","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Fonda Lee","Jade City","The Green Bone Saga","1","The Broken Binding","",false,false,""),
        new BookEntry("angielski","Fonda Lee","Jade War","The Green Bone Saga","2","The Broken Binding","",false,false,""),
        new BookEntry("angielski","Fonda Lee","Jade Legacy","The Green Bone Saga","3","The Broken Binding","",false,false,""),
        new BookEntry("angielski","James Logan","The Silverblood Promise","The Last Legacy","1","The Broken Binding","Signature, numbered",false,false,""),
        new BookEntry("angielski","James Logan","The Blackfire Blade","The Last Legacy","2","The Broken Binding","Signature, numbered",false,false,""),
        new BookEntry("angielski","Nicholas Pullen","The Black Hunger","","","The Broken Binding","Signature",false,false,""),
        new BookEntry("angielski","Michael R. Miller","Ascendant","Songs of Chaos","1","The Broken Binding","Signature",false,false,""),
        new BookEntry("angielski","Tad Williams","The Dragonbone Chair","Memory, Sorrow, and Thorn","1","The Broken Binding","",false,false,""),
        new BookEntry("angielski","Tad Williams","Stone of Farewell","Memory, Sorrow, and Thorn","2","The Broken Binding","",false,false,""),
        new BookEntry("angielski","Tad Williams","To Green Angel Tower vol. 1","Memory, Sorrow, and Thorn","3.1","The Broken Binding","",false,false,""),
        new BookEntry("angielski","Tad Williams","To Green Angel Tower vol. 2","Memory, Sorrow, and Thorn","3.2","The Broken Binding","",false,false,""),
        new BookEntry("angielski","Jennifer L. Armentrout","White Hot Kiss","The Dark Elements","1","FairyLoot","Digital signature",false,false,""),
        new BookEntry("angielski","Jennifer L. Armentrout","Stone Cold Touch","The Dark Elements","2","FairyLoot","Digital signature",false,false,""),
        new BookEntry("angielski","Jennifer L. Armentrout","Every Last Breath","The Dark Elements","3","FairyLoot","Digital signature",false,false,""),
        new BookEntry("angielski","M. A. Carrick","The Mask of Mirrors","Rook & Rose","1","The Broken Binding","",false,false,""),
        new BookEntry("angielski","M. A. Carrick","The Liar's Knot","Rook & Rose","2","The Broken Binding","",false,false,""),
        new BookEntry("angielski","M. A. Carrick","Labyrinth's Heart","Rook & Rose","3","The Broken Binding","",false,false,""),
        new BookEntry("angielski","E. K. Larson-Burnett","The Bear & the Rose","","","The Butterfly Book Club","signed bookplate",false,false,""),
        new BookEntry("angielski","Judy I. Lin","Magic Steeped in Poison","The Book of Tea","1","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Judy I. Lin","Venom Dark and Sweet","The Book of Tea","2","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Sarah Beth Durst","The Spellshop","","","OwlCrate","Signature, Bonus content",false,false,""),
        new BookEntry("angielski","Sarah JD","Insatiable Kitten","The Insatiable series","1","Romance Cartel","signed bookplate",false,true,""),
        new BookEntry("angielski","Helen Glynn Jones","The Last Raven","The Ravens","1","The Locked Library","Digital signature",false,false,""),
        new BookEntry("angielski","AJ Merlin","Pretty Little Tease","Pretty Obsessions","1","The Butterfly Book Club","signed bookplate",false,false,""),
        new BookEntry("angielski","T. Kingfisher","A Sorceress Comes to Call","","","OwlCrate","Digital signature",true,true,""),
        new BookEntry("angielski","Mariana Costa","Shoestring Theory","","","Book in a box","Digital signature",false,false,""),
        new BookEntry("angielski","Nisha J. Tuli","Wicked is the Reaper & Feral is the Beast","Cursed Capers","1 & 2","Aurora Crate Book Box","Digital signature, omnibus",false,false,""),
        new BookEntry("angielski","Seth Haddon","Reborn","The World of Reforged","2","Fae Crate","signed bookplate",false,false,""),
        new BookEntry("angielski","Lucinda Dark","A Sword of Shadow and Deceit","Mortal Gods","1","The Butterfly Book Club","signed bookplate",false,false,""),
        new BookEntry("angielski","Michelle Kulwicki","At the End of the River Styx","","","OwlCrate","Signature",false,false,""),
        new BookEntry("angielski","Jena Wolfhart","Forged by Malice","Falling For Fables","","Fae Crate","signed bookplate",false,false,""),
        new BookEntry("angielski","Mai Corland","Five Broken Blades","The Broken Blades","1","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","Mai Corland","Four Ruined Realms","The Broken Blades","2","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","Mai Corland","Three Shattered Souls","The Broken Blades","3","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","Caro De Robertis","The Palace of Eros","","","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","Alexandria Warwick","The West Wind","The Four Winds","2","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","Rosamund Hodge","What Monstrous Gods","","","The Locked Library","Digital signature",false,false,""),
        new BookEntry("angielski","Laura Steven","Every Exquisite Thing","","","The Locked Library","Digital signature",true,true,""),
        new BookEntry("angielski","Cassandra James","Capitana","","","Illumicrate","Signature, Digital signature, Bonus content",false,false,""),
        new BookEntry("angielski","Frances White","Voyage of the Damned","","","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","L. L. Macrae","The Iron Crown","Dragon Spirits","1","The Broken Binding","Signature, numbered",false,false,""),
        new BookEntry("angielski","Haley Jenner","Tangled Love","The Chaotic Rein Duet","1","Romance Cartel","signed bookplate",false,true,""),
        new BookEntry("angielski","Allison Carr Waechter","The Hollow Plane","The Aethereals Duology","1","The Bookish Box","Signature",false,false,""),
        new BookEntry("angielski","Sierra Simone","Salt Kiss","Lyonesse","1","The Bookish Box","Signature",false,true,""),
        new BookEntry("angielski","C. N. Crawford","Hallowed Games","Hallowed Games","1","The Bookish Box","Signature",false,true,""),
        new BookEntry("angielski","C. N. Crawford","Hallowed Games","Hallowed Games","1","Midnight Whispers","Signature",false,false,""),
        new BookEntry("angielski","C. N. Crawford","Vanquished Gods","Hallowed Games","2","Midnight Whispers","Signature",false,false,""),
        new BookEntry("angielski","Rob J. Hayes","Never Die","The Mortal Techniques","","Page & Wick","Signature",false,false,""),
        new BookEntry("angielski","Nnedi Okorafor","Death of the Author","","","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","Alexandra Rowland","Running Close to the Wind","","","The Bookish Box","Signature",false,false,""),
        new BookEntry("angielski","Helen Scheuerer","Iron & Embers","The Ashes of Thezmarr","1","FairyLoot","Bonus content, Signature",false,false,""),
        new BookEntry("angielski","Helen Scheuerer","Blood & Steel","The Legends of Thezmarr","1","Moonlight Book Box","Signature, slipcase",true,false,""),
        new BookEntry("angielski","Helen Scheuerer","Vows & Ruins","The Legends of Thezmarr","2","Moonlight Book Box","slipcase",false,false,""),
        new BookEntry("angielski","Helen Scheuerer","Fate & Furies","The Legends of Thezmarr","3","Moonlight Book Box","slipcase",false,false,""),
        new BookEntry("angielski","Helen Scheuerer","Shadow & Storms","The Legends of Thezmarr","4","Moonlight Book Box","slipcase",false,false,""),
        new BookEntry("angielski","Helen Scheuerer","Blood & Steel","The Legends of Thezmarr","1","The Arcane Society","Signature",true,false,""),
        new BookEntry("angielski","Helen Scheuerer","Vows & Ruins","The Legends of Thezmarr","2","The Arcane Society","",false,false,""),
        new BookEntry("angielski","Helen Scheuerer","Blood & Steel","The Legends of Thezmarr","1","The Bookish Box","Signature",true,false,""),
        new BookEntry("angielski","Helen Scheuerer","Vows & Ruins","The Legends of Thezmarr","2","The Bookish Box","Signature",false,false,""),
        new BookEntry("angielski","Helen Scheuerer","Fate & Furies","The Legends of Thezmarr","3","The Bookish Box","Signature",false,false,""),
        new BookEntry("angielski","Helen Scheuerer","Shadow & Storms","The Legends of Thezmarr","4","The Bookish Box","Signature",false,false,""),
        new BookEntry("angielski","Gareth Brown","The Book of Doors","","","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","Gareth Brown","The Society of Unknowable Objects","","","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","Alexandria Warwick","The North Wind","The Four Winds","1","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","Ruth Frances Long","The Book of Gold","The Feral Gods","1","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","Ruth Frances Long","The Lore of Silver","The Feral Gods","2","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","Susan J. Morris","Strange Beasts","Harker & Moriarty","1","Goldsboro Books","numbered, Signature",false,false,""),
        new BookEntry("angielski","Susan J. Morris","Wayward Souls","Harker & Moriarty","2","Goldsboro Books","numbered, Signature",false,false,""),
        new BookEntry("angielski","Marianne Gordon","The Gilded Crown","The Raven's Trade","1","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","Jules Arbeaux","Lord of the Empty Isles","","","Goldsboro Books","Signature, numbered",false,true,""),
        new BookEntry("angielski","Chris Sugden, Jen Sugden","High Vaultage","","","Goldsboro Books","Signature, numbered",false,true,""),
        new BookEntry("angielski","Jennifer Delaney","Tales of a Monstrous Heart","Tales of a Monstrous Heart","1","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","Jennifer Delaney","Tales of a Deadly Devotion","Tales of a Monstrous Heart","2","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","A. S. Webb","Daughter of Chaos","The Dark Pantheon","1","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","A. S. Webb","Daughter of Fate","The Dark Pantheon","2","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","Mark Lawrence","The Book That Wouldn't Burn","The Library Trilogy","1","The Locked Library","author letter",false,false,""),
        new BookEntry("angielski","Carissa Broadbent","The Ashes and the Star-Cursed King","Crowns of Nyaxia","2","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Carissa Broadbent","The Ashes and the Star-Cursed King","Crowns of Nyaxia","2","OwlCrate","Signature",false,false,""),
        new BookEntry("angielski","Prashanth Srivatsa","The Spice Gate","","","The Locked Library","Digital signature",false,false,""),
        new BookEntry("angielski","Olesya Salnikova Gilmore","The Haunting of Moscow House","","","The Locked Library","author letter",false,false,""),
        new BookEntry("angielski","Mark Lawrence","The Book That Broke the World","The Library Trilogy","2","The Locked Library","author letter",false,false,""),
        new BookEntry("angielski","Loni Crittenden","The Ancient's Game","","","The Locked Library","Digital signature",false,false,""),
        new BookEntry("angielski","antologia","The Book of Witches","","","The Locked Library","Digital signature",false,false,""),
        new BookEntry("angielski","Lilly Inkwood","The Kingdom is a Golden Cage","The Red Kingdom","1","The Locked Library","Digital signature",false,false,""),
        new BookEntry("angielski","Kyrie McCauley","Bad Graces","","","The Locked Library","Digital signature",false,true,""),
        new BookEntry("angielski","A. K. Mulford","A River of Golden Bones","","","The Locked Library","Digital signature",false,false,""),
        new BookEntry("angielski","Bridget Collins","The Silence Factory","","","The Locked Library","author letter",false,true,""),
        new BookEntry("angielski","Kate Johnson","Hex and Hexability","Hex and Hexability","3","The Locked Library","Digital signature",false,false,""),
        new BookEntry("angielski","Mary E. Pearson","Dance of Thieves","Dance of Thieves","1","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Mary E. Pearson","Vow of Thieves","Dance of Thieves","2","FairyLoot","",false,false,""),
        new BookEntry("angielski","Mary E. Pearson","The Kiss of Deception","The Remnant Chronicles","1","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Mary E. Pearson","The Heart of Betrayal","The Remnant Chronicles","2","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Mary E. Pearson","The Beauty of Darkness","The Remnant Chronicles","3","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Esmie Jikiemi-Pearson","The Principle of Moments","Order of Legends","1","Illumicrate","Signature",false,true,""),
        new BookEntry("angielski","Heather Fawcett","Emily Wilde's Map of the Otherlands","Emily Wilde","2","FairyLoot","Signature",false,true,""),
        new BookEntry("angielski","Heather Fawcett","Agnes Aubert's Mystical Cat Shelter","","","FairyLoot","Signature, author letter",false,false,""),
        new BookEntry("angielski","Renee Ahdieh","The Wrath and the Dawn","The Wrath and the Dawn","1","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Renee Ahdieh","The Rose and the Dagger","The Wrath and the Dawn","2","FairyLoot","Digital signature",false,false,""),
        new BookEntry("angielski","Laura Steven","Our Infinite Fates","","","Lilac Library","",false,true,""),
        new BookEntry("angielski","Laura Steven","Our Infinite Fates","","","OwlCrate","Signature, Bonus content",false,false,""),
        new BookEntry("angielski","Cassandra Clare","The Ragpicker King","The Chronicles of Castellane","2","Illumicrate","Digital signature",false,false,""),
        new BookEntry("angielski","Juliette Cross","Firebird","The Fire That Binds","1","FairyLoot","Signature, Digital signature, Bonus content",false,false,""),
        new BookEntry("angielski","Olivie Blake","Gifted & Talented","","","FairyLoot","Digital signature, Bonus content",false,false,""),
        new BookEntry("angielski","Kell Woods","Upon a Starlit Tide","","","OwlCrate","Bonus content, Signature",false,false,""),
        new BookEntry("angielski","Vanessa Rasanen","Until the Stars Fall","Immortal Reveries","1","The Bookish Box","Signature, fore-edge design",false,false,""),
        new BookEntry("angielski","Vanessa Rasanen","Once the Skies Fade","Immortal Reveries","2","The Bookish Box","Signature, fore-edge design",false,false,""),
        new BookEntry("angielski","K. C. Kean","Falling Shadows","Silvercrest Academy","1","Romance Cartel","signed bookplate",true,false,""),
        new BookEntry("angielski","K. C. Kean","Destined Shadows","Silvercrest Academy","2","Romance Cartel","",false,false,""),
        new BookEntry("angielski","K. C. Kean","Cursed Shadows","Silvercrest Academy","3","Romance Cartel","",false,false,""),
        new BookEntry("angielski","K. C. Kean","Unchained Shadows","Silvercrest Academy","4","Romance Cartel","",false,false,""),
        new BookEntry("angielski","Scarlett St. Clair","A Touch of Darkness","Hades x Persephone Series","1","FairyLoot","Signature, Annotated",true,false,""),
        new BookEntry("angielski","Scarlett St. Clair","A Touch of Ruin","Hades x Persephone Series","2","FairyLoot","Digital signature, Annotated",false,false,""),
        new BookEntry("angielski","Scarlett St. Clair","A Touch of Malice","Hades x Persephone Series","3","FairyLoot","Digital signature, Annotated",false,false,""),
        new BookEntry("angielski","Scarlett St. Clair","A Touch of Chaos","Hades x Persephone Series","4","FairyLoot","Digital signature, Annotated",false,false,""),
        new BookEntry("angielski","Scarlett St. Clair","King of Battle and Blood","Adrian x Isolde","1","The Arcane Society","",false,false,""),
        new BookEntry("angielski","Scarlett St. Clair","Queen of Myth and Monsters","Adrian x Isolde","2","The Arcane Society","",false,false,""),
        new BookEntry("angielski","Sarah Hawley","A Servant of Earth","The Shards of Magic","1","Book in a box","signed bookplate",false,false,""),
        new BookEntry("angielski","Nicole Blanchard","Toxic","","","The Butterfly Book Club","signed bookplate",false,false,""),
        new BookEntry("angielski","Nicole Platania","The Curse of Ophelia","The Curse of Ophelia","1","The Butterfly Book Club","signed bookplate",false,false,""),
        new BookEntry("angielski","Kell Woods","After The Forest","After The Forest","1","Illumicrate","",false,false,""),
        new BookEntry("angielski","Zavi James","Of Gods & Monsters","Elysian Gods","1","The Butterfly Book Club","signed bookplate",false,false,""),
        new BookEntry("angielski","Nicole M. Rubino","Monstrous","Monstrous","1","The Butterfly Book Club","signed bookplate, Bonus content",false,false,""),
        new BookEntry("angielski","H. E. Edgmon","Godly Heathens","The Ouroboros","1","The Bookish Box","Signature",false,true,""),
        new BookEntry("angielski","M. Violet","Pretty Little Psycho","Devils of Raven's Gate","1","The Butterfly Book Club","signed bookplate",false,false,""),
        new BookEntry("angielski","Alexandra Christo","The Night Hunt","","","The Bookish Box","Signature",false,false,""),
        new BookEntry("angielski","Kel Carpenter, Aurelia Jane","Mate Me","Immortal Vices and Virtues","1","The Butterfly Book Club","signed bookplate",false,false,""),
        new BookEntry("angielski","Lucy Score","The Dead Guy Next Door","Riley Thorn","1","The Bookish Box","Digital signature",false,true,""),
        new BookEntry("angielski","Greta Kelly","The Queen of Days","","","LitJoy Crate","Signature, Digital signature",false,false,""),
        new BookEntry("angielski","Kalyn Josephson","This Dark Descent","This Dark Descent","1","OwlCrate","Signature",false,true,""),
        new BookEntry("angielski","Aurora Asher","Sanctuary of the Shadow","Elemental Emergence","1","The Bookish Box","Signature",false,false,""),
        new BookEntry("angielski","Chloe C. Penaranda","The Stars are Dying","Nytefall","1","The Bookish Box","Signature",false,false,""),
        new BookEntry("angielski","Chloe C. Penaranda","The Night is Defying","Nytefall","2","The Bookish Box","Signature",false,false,""),
        new BookEntry("angielski","Analeigh Sbrana","Lore of the Wilds","Lore of the Wilds","1","The Bookish Box","Signature",false,false,""),
        new BookEntry("angielski","Alexis L. Menard","House of Bane and Blood","Order and Chaos","1","The Bookish Box","Signature",true,true,""),
        new BookEntry("angielski","Karina Halle","Blood Orange","The Dracula Duet","1","The Arcane Society","Signature",false,false,""),
        new BookEntry("angielski","Karina Halle","Black Rose","The Dracula Duet","2","The Arcane Society","",false,false,""),
        new BookEntry("angielski","Whit Stanfield","A Sea of Song and Sirens","The Naiads of Juile","1","Coveted Cover","Signature, overlays",false,false,""),
        new BookEntry("angielski","Harper L. Woods","The Coven","The Coven of Bones","1","Midnight Whispers","Signature",false,false,""),
        new BookEntry("angielski","Harper L. Woods","The Cursed","The Coven of Bones","2","Midnight Whispers","Signature",false,false,""),
        new BookEntry("angielski","Lyra Asher","Heart of the Marked","Moons of the Divine","1","Midnight Whispers","Signature",false,false,""),
        new BookEntry("angielski","Lyra Asher","Queen of the Broken","Moons of the Divine","2","Midnight Whispers","Signature",false,false,""),
        new BookEntry("angielski","Lyra Asher","Blood of the Divine","Moons of the Divine","3","Midnight Whispers","Signature",false,false,""),
        new BookEntry("angielski","Melissa K. Roehrich","Rain of Shadows and Endings","The Legacy Series","1","Midnight Whispers","Signature",false,false,""),
        new BookEntry("angielski","Melissa K. Roehrich","Storm of Secrets and Sorrow","The Legacy Series","2","Midnight Whispers","Digital signature",false,false,""),
        new BookEntry("angielski","Melissa K. Roehrich","Lady of Darkness","Lady of Darkness","1","The Arcane Society","Signature",false,false,""),
        new BookEntry("angielski","Melissa K. Roehrich","Lady of Shadows","Lady of Darkness","2","The Arcane Society","",false,false,""),
        new BookEntry("angielski","Melissa K. Roehrich","Lady of Ashes","Lady of Darkness","3","The Arcane Society","",false,false,""),
        new BookEntry("angielski","Melissa K. Roehrich","Lady of Embers","Lady of Darkness","4","The Arcane Society","",false,false,""),
        new BookEntry("angielski","Melissa K. Roehrich","Lady of Starfire","Lady of Darkness","5","The Arcane Society","",false,false,""),
        new BookEntry("angielski","Ivy Asher, Ann Denton","Into Their Woods","The Eerie","1","The Arcane Society","Signature",true,false,""),
        new BookEntry("angielski","Ivy Asher","The Bone Witch, The Blood Witch, The Bound Witch","The Osseous Chronicles","1-3","The Arcane Society","Signature, omnibus",false,false,""),
        new BookEntry("angielski","Shannon Mayer","Golden","The Golden Wolf series","1","The Arcane Society","Signature",false,false,""),
        new BookEntry("angielski","Shannon Mayer","Glitter","The Golden Wolf series","2","The Arcane Society","",false,false,""),
        new BookEntry("angielski","Shannon Mayer","Gossamer","The Golden Wolf series","3","The Arcane Society","",false,false,""),
        new BookEntry("angielski","Amber Chen","Of Jade and Dragons","Fall of the Dragon","1","Illumicrate","Signature",false,true,""),
        new BookEntry("angielski","Robert Jackson Bennett","The Tainted Cup","Shadow of the Leviathan","1","The Broken Binding","Signature, numbered",false,false,""),
        new BookEntry("angielski","Robert Jackson Bennett","A Drop of Corruption","Shadow of the Leviathan","2","The Broken Binding","Signature, numbered",false,false,""),
        new BookEntry("angielski","Courtney Gould","What the Woods Took","","","OwlCrate","Bonus content, Signature",false,false,""),
        new BookEntry("angielski","Cassandra Clare","Sword Catcher","The Chronicles of Castellane","1","Illumicrate","Digital signature",false,false,""),
        new BookEntry("angielski","Kate Dylan","Until We Shatter","Until We Shatter","1","Illumicrate","Signature, Bonus content",false,true,""),
        new BookEntry("angielski","Mina Fears","The Scorpion Queen","","","OwlCrate","Signature",false,true,""),
        new BookEntry("angielski","S. A. MacLean","The Phoenix Keeper","","","Illumicrate","Signature",false,false,""),
        new BookEntry("angielski","Ella Dawes","To Bleed a Kingdom","The Bleeding Realms","1","Fabled Co","Signature",false,false,""),
        new BookEntry("angielski","Bea Northwick","The Cruel Dark","The Cruel Dark","1","Fabled Co","Signature",false,false,""),
        new BookEntry("angielski","Allison Saft","A Dark and Drowning Tide","","","Illumicrate","Signature, Bonus content",false,false,""),
        new BookEntry("angielski","Madeline Te Whiu","The Assassin Thief","The Soul Thief Trilogy","1","Bookish & Spice","signed bookplate",false,false,""),
        new BookEntry("angielski","Eliza Chan","Fathomfolk","Drowned World","1","Illumicrate","Signature",false,false,""),
        new BookEntry("angielski","Rachel Greenlaw","Compass and Blade","Compass and Blade","1","The Locked Library","Digital signature",false,false,""),
        new BookEntry("angielski","Mark Holloway","The Soul's Aspect","The Aspect","1","Page & Wick","Signature",false,false,""),
        new BookEntry("angielski","Emilia Hart","The Sirens","","","The Locked Library","Digital signature",true,true,""),
        new BookEntry("angielski","Evie Marceau","White Horse Black Nights","The Godkissed Bride","1","The Bookish Box","Signature",false,false,""),
        new BookEntry("angielski","Kristen Ciccarelli","Rebel Witch","The Crimson Moth","2","OwlCrate","Signature, Bonus content",true,false,""),
        new BookEntry("angielski","Tessa Hale","Twilight of Embers, Dawn of Flames, Midnight of Ashes","Dragons of Ember Hollow","1-3","The Bookish Box","Signature, omnibus",false,false,""),
        new BookEntry("angielski","Romina Garber","Castle of the Cursed","","","OwlCrate","Signature, Bonus content",false,false,""),
        new BookEntry("angielski","Beka Westrup","Demons & Roses","The Eternal Brides","1","Fabled Co","Signature",false,false,""),
        new BookEntry("angielski","Heather Smith","Stars Ascending","","","Fabled Co","Signature",false,false,""),
        new BookEntry("angielski","Sasha Peyton Smith","The Rose Bargain","","","FairyLoot","Digital signature",false,false,""),
        new BookEntry("angielski","Miranda Joy","Shades of Silver City","","","Fabled Co","Signature",false,false,""),
        new BookEntry("angielski","Lauren Jackson","Die for You","Red Thorne","1","Bookish & Spice","",false,false,""),
        new BookEntry("angielski","Lauren Jackson","Live for You","Red Thorne","2","Bookish & Spice","signed bookplate",false,false,""),
        new BookEntry("angielski","Lindsey Kelk","The Bell Witches","Savannah Red","1","The Locked Library","Digital signature",false,false,""),
        new BookEntry("angielski","Amalie Howard","The Starlight Heir","","","FairyLoot","Digital signature",false,false,""),
        new BookEntry("angielski","Tetyana Walker","A Broken Promise","Freckled Fate","1","Fabled Co","Signature",false,false,""),
        new BookEntry("angielski","Mary E. Pearson","The Courting of Bristol Keats","The Courting of Bristol Keats","1","The Bookish Box","Digital signature",false,true,""),
        new BookEntry("angielski","Sophie Clark","Cruel Is the Light","Cruel is the Light","1","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Tricia Levenseller","The Darkness Within Us","The Shadows Between Us","2","FairyLoot","Digital signature, Bonus content",false,false,""),
        new BookEntry("angielski","Tricia Levenseller","The Shadows Between Us","The Shadows Between Us","1","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Tricia Levenseller","What Fury Brings","Wrath and Fury","1","OwlCrate","Signature",false,false,""),
        new BookEntry("angielski","Tricia Levenseller","What Fury Brings","Wrath and Fury","1","The Bookish Box","Signature",false,false,""),
        new BookEntry("angielski","Kalynn Bayron","Sleep Like Death","","","FairyLoot","Digital signature, Bonus content",false,true,""),
        new BookEntry("angielski","Harper Hawthorne","Of Blood and Aether","Harbingers","1","Fabled Co","Signature",false,false,""),
        new BookEntry("angielski","Emily Varga","For She Is Wrath","","","FairyLoot","Digital signature, Bonus content",false,true,""),
        new BookEntry("angielski","Imani Erriu","Heavenly Bodies","Heavenly Bodies","1","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Imani Erriu","Fallen Stars","Heavenly Bodies","2","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","S. Massery","The Pucking Coach's Daughter","","","Fabled Co","Signature",false,true,""),
        new BookEntry("angielski","June CL Tan","Darker by Four","Darker by Four","1","FairyLoot","Bonus content",false,true,""),
        new BookEntry("angielski","Tessonja Odette","A Throne of Shadows","Prophecy of the Forgotten Fae","1","Fabled Co","Signature",false,false,""),
        new BookEntry("angielski","Harper L. Woods","The Coven","The Coven of Bones","1","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Sabaa Tahir","Heir","Heir Duology","1","FairyLoot","overlays",false,false,""),
        new BookEntry("angielski","Elizabeth May","To Cage a God","These Monstrous Gods","1","Illumicrate","Signature, Bonus content",false,false,""),
        new BookEntry("angielski","Natalia Jaster","Trick","Foolish Kingdoms","1","Bookish & Spice","signed bookplate",false,false,""),
        new BookEntry("angielski","Maiga Doocy","Sorcery and Small Magics","The Wildersongs Trilogy","1","FairyLoot","Digital signature, Bonus content",false,false,""),
        new BookEntry("angielski","Sydney J. Shields","The Honey Witch","","","FairyLoot","Digital signature",false,false,""),
        new BookEntry("angielski","Harley Laroux","Her Soul to Take","Souls Trilogy","1","Page & Wick","Signature",true,false,""),
        new BookEntry("angielski","Leigh Bardugo","The Familiar","","","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Miranda Sun","If I Have To Be Haunted","","","FairyLoot","Digital signature, Bonus content",false,false,""),
        new BookEntry("angielski","Molly X. Chang","To Gaze Upon Wicked Gods","Gods Beyond the Skies","1","Illumicrate","Signature",false,true,""),
        new BookEntry("angielski","Lauren Wiesebron","The House of Frost and Feathers","","","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","Melissa Caruso","The Last Hour Between Worlds","The Echo Archives","1","Illumicrate","Signature",false,true,""),
        new BookEntry("angielski","Georgia Summers","The City of Stardust","","","FairyLoot","Digital signature",false,false,""),
        new BookEntry("angielski","Andrea Stewart","The Gods Below","The Hollow Covenant","1","FairyLoot","Digital signature",false,false,""),
        new BookEntry("angielski","Allison Saft","A Fragile Enchantment","","","FairyLoot","Digital signature, Bonus content",false,false,""),
        new BookEntry("angielski","Megan Scott","The Temptation of Magic","Empyreal","1","FairyLoot","Digital signature, Bonus content",false,false,""),
        new BookEntry("angielski","Caitlin Starling","Last To Leave the Room","","","Illumicrate","",false,false,""),
        new BookEntry("angielski","Danielle L. Jensen","A Fate Inked In Blood","Saga of the Unfated","1","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Danielle L. Jensen","A Curse Carved in Bone","Saga of the Unfated","2","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Danielle L. Jensen","A Fate Inked In Blood","Saga of the Unfated","1","The Arcane Society","Signature",false,false,""),
        new BookEntry("angielski","Keshe Chow","The Girl With No Reflection","","","FairyLoot","Bonus content, author letter",false,true,""),
        new BookEntry("angielski","K. X. Song","The Night Ends with Fire","The Night Ends with Fire","1","FairyLoot","author letter, Bonus content",false,true,""),
        new BookEntry("angielski","Adrienne Young","The Unmaking of June Farrow","","","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Melissa Landers","The Half King","The Half King","1","FairyLoot","Signature, author letter, Bonus content",false,false,""),
        new BookEntry("angielski","Samantha Sotto Yambao","Water Moon","","","Illumicrate","Signature, author letter",false,true,""),
        new BookEntry("angielski","Sarah Rees Brennan","Long Live Evil","Time of Iron","1","FairyLoot","author letter, Bonus content",false,false,""),
        new BookEntry("angielski","Makana Yamamoto","Hammajang Luck","","","Illumicrate","Signature",false,true,""),
        new BookEntry("angielski","Amelie Wen Zhao","The Scorpion and the Night Blossom","The Three Realms Duology","1","FairyLoot","author letter, Bonus content",false,true,""),
        new BookEntry("angielski","S. T. Gibson","Evocation","The Summoner's Circle","1","FairyLoot","Signature, Bonus content",true,true,""),
        new BookEntry("angielski","V. B. Lacey","Long Live Forever Reign","The Elementals of Iona","1-2","Moonlight Book Box","omnibus, Signature, overlays",false,false,""),
        new BookEntry("angielski","S. M. Gaither","Flame & Sparrow","Flame & Sparrow Duology","1","The Bookish Box","Signature",false,true,""),
        new BookEntry("angielski","K. M. Enright","Mistress of Lies","The Age of Blood","1","Illumicrate","Digital signature, author letter",false,false,""),
        new BookEntry("angielski","K. M. Enright","Lord of Ruin","The Age of Blood","2","Illumicrate","author letter",false,false,""),
        new BookEntry("angielski","Constanza Casti","Babylonia","","","Page & Wick","Signature",false,false,""),
        new BookEntry("angielski","Lilian T. James","Into the Wonder Dark","","","Fabled Co","Signature, Bonus content",false,false,""),
        new BookEntry("angielski","Diana Wynne Jones","Howl's Moving Castle","Howl's Moving Castle","1","FairyLoot","",false,false,""),
        new BookEntry("angielski","Diana Wynne Jones","Castle in the Air","Howl's Moving Castle","2","FairyLoot","",false,false,""),
        new BookEntry("angielski","Diana Wynne Jones","House of Many Ways","Howl's Moving Castle","3","FairyLoot","",false,false,""),
        new BookEntry("angielski","Saara El-Arifi","Faebound","Faebound","1","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","Saara El-Arifi","Cursebound","Faebound","2","Goldsboro Books","Signature, numbered",false,false,""),
        new BookEntry("angielski","H. E. Edgmon","Godly Heathens","The Ouroboros","1","Illumicrate","Signature",false,false,""),
        new BookEntry("angielski","H. E. Edgmon","Merciless Saviors","The Ouroboros","2","Illumicrate","Signature",false,false,""),
        new BookEntry("angielski","Gabriela Romero Lacruz","The Sun and the Void","The Warring Gods","1","Illumicrate","Signature",false,true,""),
        new BookEntry("angielski","Nicki Pau Preto","Bonesmith","The Dead Duology","1","FairyLoot","Digital signature",true,false,""),
        new BookEntry("angielski","Nicki Pau Preto","Ghostsmith","The Dead Duology","2","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Vaishnavi Patel","Goddess of the River","","","Illumicrate","Digital signature",false,false,""),
        new BookEntry("angielski","Rin Chupeco","The Bone Witch","The Bone Witch","1","Illumicrate","Signature",false,false,""),
        new BookEntry("angielski","Rin Chupeco","The Heart Forger","The Bone Witch","2","Illumicrate","Digital signature",false,false,""),
        new BookEntry("angielski","Rin Chupeco","The Shadowglass","The Bone Witch","3","Illumicrate","Digital signature",false,false,""),
        new BookEntry("angielski","Erin Morgenstern","The Starless Sea","","","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Erin Morgenstern","The Night Circus","","","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Kerri Maniscalco","Throne of Secrets","Prince of Sin","2","FairyLoot","Digital signature",false,false,""),
        new BookEntry("angielski","Isabel Ibanez","What the River Knows","Secrets of the Nile","1","OwlCrate","Signature, author letter, Bonus content",false,false,""),
        new BookEntry("angielski","Isabel Ibanez","What the Library Hides","Secrets of the Nile","2","OwlCrate","Signature, author letter",false,false,""),
        new BookEntry("angielski","Laini Taylor","Strange the Dreamer","Strange the Dreamer","","Illumicrate","Signature",false,false,""),
        new BookEntry("angielski","Laini Taylor","Muse of Nightmares","Strange the Dreamer","","Illumicrate","Signature",false,false,""),
        new BookEntry("angielski","S. M. Gaither","The Song of the Marked","Shadows and Crowns","1","Aurora Crate Book Box","signed bookplate",false,false,""),
        new BookEntry("angielski","S. M. Gaither","A Twist of the Blade","Shadows and Crowns","2","Aurora Crate Book Box","signed bookplate",false,false,""),
        new BookEntry("angielski","S. M. Gaither","The Call of the Void","Shadows and Crowns","3","Aurora Crate Book Box","signed bookplate",false,false,""),
        new BookEntry("angielski","Briar Boleyn","Queen of Roses","Blood of a Fae","1","Aurora Crate Book Box","signed bookplate",false,false,""),
        new BookEntry("angielski","Stephanie Burgis","Wooing the Witch Queen","Queens of Villainy","1","OwlCrate","Signature, author letter",false,false,""),
        new BookEntry("angielski","Kellen Graves","A Bone In His Teeth","","","Fae Crate","Signature",false,false,""),
        new BookEntry("angielski","D. L. Taylor","The Beasts We Bury","The Broken Citadel","1","OwlCrate","Signature, Bonus content, author letter",false,false,""),
        new BookEntry("angielski","TJ Klune","The House in the Cerulean Sea","Cerulean Chronicles","1","Illumicrate","Digital signature",false,false,""),
        new BookEntry("angielski","TJ Klune","Somewhere Beyond the Sea","Cerulean Chronicles","2","Illumicrate","Signature",false,false,""),
        new BookEntry("angielski","TJ Klune","Under the Whispering Door","","1","Illumicrate","Digital signature",false,false,""),
        new BookEntry("angielski","TJ Klune","In The Lives of Puppets","","2","Illumicrate","Signature",false,false,""),
        new BookEntry("angielski","Jenny Hickman","A Cursed Kiss","Myths of Airren","1","The Butterfly Book Club","signed bookplate",false,false,""),
        new BookEntry("angielski","Jenny Hickman","A Cursed Heart","Myths of Airren","2","The Butterfly Book Club","signed bookplate",false,false,""),
        new BookEntry("angielski","Jenny Hickman","A Cursed Love","Myths of Airren","3","The Butterfly Book Club","signed bookplate",false,false,""),
        new BookEntry("angielski","Jenny Hickman","Bound by Gravity","Bound and Freed","1","Midnight Whispers","Signature",false,false,""),
        new BookEntry("angielski","Jenny Hickman","Freed from Gravity","Bound and Freed","2","Midnight Whispers","Signature",false,false,""),
        new BookEntry("angielski","Rebecca F. Kenney","A Hunt so Wild and Cruel","Mythic Holidays","1","Moonlight Book Box","Signature",false,false,""),
        new BookEntry("angielski","Clare Sager","A Kiss of Iron","Shadows of the Tenebris Court","1","The Bookish Box","Digital signature, Bonus content",false,false,""),
        new BookEntry("angielski","Clare Sager","King of Ravens","Upon a Broken Throne","1","FairyLoot","Digital signature, author letter, Bonus content",false,false,""),
        new BookEntry("angielski","Tigest Girma","Immortal Dark","Immortal Dark Trilogy","1","OwlCrate","overlays, Signature, author letter",false,false,""),
        new BookEntry("angielski","Samantha Sotto Yambao","Water Moon","","","OwlCrate","Signature, author letter, Bonus content",false,true,""),
        new BookEntry("angielski","Melissa Kieran","A Warrior's Fate","Wolves of Morai","1","Moonlight Book Box","Signature, overlays",false,false,""),
        new BookEntry("angielski","Mikayla D. Hornedo","Blood & Brujas","Fate of the Acna","1","Fae Crate","Signature",false,false,""),
        new BookEntry("angielski","Kaydence Snow","Just Be Her","","","Romance Cartel","signed bookplate",false,false,""),
        new BookEntry("angielski","Lauren Blackwood","The Dangerous Ones","","","Fae Crate","signed bookplate",false,false,""),
        new BookEntry("angielski","K. A. Knight","Court of Nightmares","Courts & Kings","1","The Bookish Box","Digital signature",true,false,""),
        new BookEntry("angielski","Anna Carven","Embers in the Snow","","","Moonlight Book Box","Signature",false,false,""),
        new BookEntry("angielski","Catherine Doyle","The Dagger and the Flame","The City of Fantome","1","FairyLoot","Bonus content, author letter",true,false,""),
        new BookEntry("angielski","LJ Andrews","The Ever King","The Ever Seas","1","The Arcane Society","Signature",false,false,""),
        new BookEntry("angielski","LJ Andrews","The Ever Queen","The Ever Seas","2","The Arcane Society","",false,false,""),
        new BookEntry("angielski","Jade West","The Naughty List","Naughtier and Naughtier","1-2","Romance Cartel","omnibus, signed bookplate",false,false,""),
        new BookEntry("angielski","Tate James, Heather Long","I'll be Home","","","Romance Cartel","signed bookplate",false,true,""),
        new BookEntry("angielski","Katie Galvin","The Gifted","The Gifted","1","The Locked Library","author letter",false,false,""),
        new BookEntry("angielski","Stacia Stark","Speak of the Demon","Deals with Demons","1","Aurora Crate Book Box","signed bookplate",false,false,""),
        new BookEntry("angielski","Stacia Stark","Dance with the Demon","Deals with Demons","2","Aurora Crate Book Box","signed bookplate",false,false,""),
        new BookEntry("angielski","Stacia Stark","Inner Demons","Deals with Demons","3","Aurora Crate Book Box","signed bookplate",false,false,""),
        new BookEntry("angielski","A. T. Qureshi","The Baby Dragon Cafe","The Baby Dragon","1","The Locked Library","author letter",false,false,""),
        new BookEntry("angielski","A. T. Qureshi","The Baby Dragon Bakery","The Baby Dragon","2","The Locked Library","author letter",false,false,""),
        new BookEntry("angielski","Sung-Il Kim","Blood of the Old Kings","The Bleeding Empire","","Fae Crate","Signature",false,true,""),
        new BookEntry("angielski","Rose Szabo","We All Fall Down","The River City Duology","1","Illumicrate","Signature",false,false,""),
        new BookEntry("angielski","Ava Reid","A Study in Drowning","A Study in Drowning","","Illumicrate","Signature",true,true,""),
        new BookEntry("angielski","Taran Matharu","Dragon Rider","The Soulbound Saga","1","Goldsboro Books","Signature, numbered",true,true,""),
        new BookEntry("angielski","Bethany Baptiste","The Poisons We Drink","","","Fabled Co","Signature",false,false,""),
        new BookEntry("angielski","Stacy Marie Brown","Silver Tongue Devil & Devil in Boots","Devil in the Deep Blue Sea","1-2","The Bookish Box","omnibus, Digital signature",false,false,""),
        new BookEntry("angielski","Tessia Ives","A Moonrise in the Fire","An Element of Fire","1","Fabled Co","Digital signature",false,false,""),
        new BookEntry("angielski","Maggie Sunseri","Taken by Touch and Torment","Eternal Obsession","2","Fae Crate","Signature",false,false,""),
        new BookEntry("angielski","Maggie Sunseri","Stalked by Seduction and Shadows","Eternal Obsession","1","Fabled Co","",false,false,""),
        new BookEntry("angielski","Amy Avery","The Longest Autumn","","","OwlCrate","Signature, author letter, Bonus content",false,false,""),
        new BookEntry("angielski","Katherine Arden","The Warm Hands of Ghosts","","","OwlCrate","Signature, author letter, Bonus content",false,false,""),
        new BookEntry("angielski","Pierce Brown","Red Rising","Red Rising Saga","1","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Pierce Brown","Golden Son","Red Rising Saga","2","FairyLoot","Digital signature",false,false,""),
        new BookEntry("angielski","Pierce Brown","Morning Star","Red Rising Saga","3","FairyLoot","Digital signature",false,false,""),
        new BookEntry("angielski","Zeba Shahnaz","Midnight Strikes","","","OwlCrate","Signature, author letter, Bonus content",false,false,""),
        new BookEntry("angielski","Emily J. Taylor","Hotel Magnifique","","","OwlCrate","Signature",false,false,""),
        new BookEntry("angielski","Ali Hazelwood","Bride","Bride","1","OwlCrate","Signature, author letter, Bonus content",true,false,""),
        new BookEntry("angielski","Ali Hazelwood","Mate","Bride","2","OwlCrate","Digital signature",false,false,""),
        new BookEntry("angielski","Jennifer L. Armentrout","Fall of Ruin and Wrath","Awakening","1","OwlCrate","Digital signature",false,false,""),
        new BookEntry("angielski","Lyssa Mia Smith","Revelle","","","OwlCrate","Signature, author letter",false,false,""),
        new BookEntry("angielski","Kendare Blake","Girl of Nightmares","Anna","2","OwlCrate","Signature, Bonus content",false,false,""),
        new BookEntry("angielski","Vanessa Len","Only a Monster","Monsters","1","OwlCrate","Signature",false,false,""),
        new BookEntry("angielski","Chloe Gong","Immortal Longings","Flesh and False Gods","1","OwlCrate","Signature, Bonus content",false,false,""),
        new BookEntry("angielski","Katy Rose Pool","Garden of the Cursed","Garden of the Cursed","1","OwlCrate","Signature, author letter",false,false,""),
        new BookEntry("angielski","Katy Rose Pool","Masquerade of the Heart","Garden of the Cursed","2","OwlCrate","Signature, author letter, Bonus content",false,false,""),
        new BookEntry("angielski","Laura R. Samotin","The Sins on Their Bones","The Cursed Crown","1","OwlCrate","Signature, author letter, Bonus content",false,false,""),
        new BookEntry("angielski","Tara Sim","The City of Dusk","The Dark Gods","1","FairyLoot","Signature",false,false,""),
        new BookEntry("angielski","Tara Sim","Midnight Kingdom","The Dark Gods","2","FairyLoot","",false,false,""),
        new BookEntry("angielski","Mackenzy Fox, Dakotah Fox","Snowed Out","","","Romance Cartel","signed bookplate",false,false,""),
        new BookEntry("angielski","Genoveva Dimova","Foul Days","The Witch's Compendium of Monsters","1","OwlCrate","Signature, author letter, Bonus content",false,false,""),
        new BookEntry("angielski","Genoveva Dimova","Monstrous Nights","The Witch's Compendium of Monsters","2","OwlCrate","Signature, author letter, Bonus content",false,false,""),
        new BookEntry("angielski","Sara Raasch","The Nightmare Before Kissmas","Royals and Romance","1","OwlCrate","Signature, author letter",false,false,""),
        new BookEntry("angielski","Mara Rutherford","The Poison Season","","","OwlCrate","Signature",false,false,""),
        new BookEntry("angielski","Katherine Quinn","To Kill a Shadow","Mistlands","1","OwlCrate","Signature, author letter, Bonus content",false,false,"")
    );

    @GetMapping
    public List<BookEntry> getCollection() {
        return BOOKS;
    }
}
