-- Seed feature_categories (46 categories)
-- Only inserts if the table is empty, so it is safe to run on production
-- and will not overwrite any manually edited categories.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM feature_categories LIMIT 1) THEN
    INSERT INTO feature_categories (id, slug, label, "group", "sortOrder", "includePatterns", "excludePatterns", "isActive", "createdAt", "updatedAt")
    VALUES
    ('9e25eec3-d524-4460-b76a-b987e80e0bec', 'author_letter_signed', 'Author Letter with Signature', 'signed', 0, '["\\bauthor letter with.{0,10}digital signature\\b", "\\bbound.?in author letter with.{0,10}digital signature\\b", "\\bbound in author letter with.{0,10}digital signature\\b", "\\bbound.?in letter with.{0,10}digital signature\\b", "\\bbound in letter with.{0,10}digital signature\\b", "\\bbound.?in letter from the author with.{0,10}digital signature\\b", "\\bdigitally signed author letter\\b", "\\bdigit\\w+ signed.{0,20}letter\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('e9e7513c-c16e-4754-97c0-d76611662f99', 'signed', 'Signed', 'signed', 1, '["\\bhand[- ]?signed\\b", "\\bhand signature\\b", "\\bsigned tip[- ]?in\\b", "\\bsigned page\\b", "\\bsigned endpapers?\\b", "\\bsigned end papers?\\b", "\\bsigned by the author\\b", "\\bsigned by the artist\\b", "\\bsigned copies\\b", "\\bsigned \\(limited\\)\\b", "\\bsigned for\\b", "\\bexclusively designed signed\\b", "\\bfirst 500 signed\\b", "^signed$", "\\bsigned by the artists\\b"]'::jsonb, '["\\bdigitally signed\\b", "\\bbookplate\\b", "\\bautopen\\b", "\\bstamped\\b"]'::jsonb, true, NOW(), NOW()),
    ('4197078f-6f14-4d67-97a3-0b7bff1a9a98', 'digitally_signed', 'Digital Signature', 'signed', 2, '["\\bdigital signature\\b", "\\bdigital signatures\\b", "\\bdigitally signed\\b", "\\bdigital sig\\b", "\\bfoiled digital signature\\b", "\\bprinted signature\\b", "\\bdigital author signature\\b"]'::jsonb, '["\\bdigitally designed edges\\b", "\\bdigitally printed\\b", "\\bdigitally sprayed\\b", "\\bauthor letter\\b", "\\bletter from the author\\b", "\\bbound.?in letter\\b", "\\bbound in letter\\b", "\\binbound letter\\b", "\\bdigitally signed author letter\\b"]'::jsonb, true, NOW(), NOW()),
    ('88f0cd21-0492-4730-82f3-c831cb5c2ccf', 'signed_bookplate', 'Signed Bookplate', 'signed', 3, '["\\bbookplates?\\b", "\\bbookplated\\b", "\\bsigned overlay\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('f1271246-6fe8-476a-ba9e-afa8eb20a3e3', 'autopen_signature', 'Autopen Signature', 'signed', 4, '["\\bautopen\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('9f7ecc2c-2fc3-4be6-a677-4679aa9042d7', 'stamped_signature', 'Stamped Signature', 'signed', 5, '["\\bstamped signature\\b", "\\bhand.?stamped author signature\\b", "\\bstamped author\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('e41118f1-cfc3-4776-968d-f961a03410e1', 'author_signature_page', 'Author Signature Page', 'interior', 6, '["\\bauthor signature page\\b", "\\bsignature page\\b", "\\bsigned tip.?in page\\b"]'::jsonb, '["\\bdesign\\b"]'::jsonb, true, NOW(), NOW()),
    ('24d33842-c65e-4fa4-a669-f4ef216cda8b', 'edges_printed', 'Printed/Digital Edges', 'edges', 7, '["\\bdigitally printed\\b", "\\bdigital printed\\b", "\\bedges? printed\\b", "\\bprinted edges?\\b", "\\bprinted fore.?edge\\b", "\\bprinted edge\\b", "\\bdigital edges?\\b", "\\bdigitally designed edges\\b", "\\bedge design\\b", "\\bedge designs\\b", "\\bedges? artwork\\b", "\\bexclusive edges\\b", "\\bexclusive edge design\\b", "\\bexclusive redesigned edges\\b", "\\bbeautiful digi edges\\b", "\\bedges\\b"]'::jsonb, '["\\bstencil\\w*\\b", "\\bgilded\\b", "\\bgolden\\b", "\\bsilver gilded\\b", "\\bholographic edges\\b", "\\blaser etched\\b", "\\bfore.?edge artwork\\b", "\\bhidden\\b", "\\bcontinuous edge\\b", "\\bseries connected\\b", "\\bline up with\\b", "\\bonly sprayed\\b", "\\bsolid sprayed\\b", "\\bsprayed edges\\b"]'::jsonb, true, NOW(), NOW()),
    ('817bcb9b-68f9-45ff-8da0-8f451d64cbdd', 'edges_sprayed', 'Sprayed Edges', 'edges', 8, '["\\bsprayed edges?\\b", "\\bedges sprayed\\b", "\\bspray top\\b", "\\bspray bottom\\b", "\\bblock sprayed\\b", "\\bblock-sprayed\\b", "\\bsolid sprayed\\b", "\\bombre sprayed\\b", "\\bomre stayed edges\\b", "\\bdigital sprayed\\b", "\\bdigitally sprayed\\b", "\\bsolid top and bottom edges\\b", "\\bsolid spray top and bottom\\b", "\\bblock.?printed top\\b", "\\bsprayed top and bottom\\b", "\\bsolid top and bottom\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('eee1d3dc-1eef-47ff-9394-d0e64731d73a', 'edges_stenciled', 'Stenciled Edges', 'edges', 9, '["\\bstenciled? edges?\\b", "\\bstencilled? edges?\\b", "\\bstencil sprayed\\b", "\\bstencil\\b", "\\bstenciled\\b", "\\bstencilled\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('21205700-98ba-4197-9fd7-7c2d3b052823', 'foiled_edges', 'Foiled/Gilded Edges', 'edges', 10, '["\\bgilded edges\\b", "\\bgilded edge\\b", "\\bsilver gilded\\b", "\\bgolden gilded\\b", "\\bfoiled edges\\b", "\\bholographic edges\\b", "\\blaser etched edge\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('be37aaeb-475d-4e1b-9037-27f010bef3fa', 'foredge_design', 'Fore-Edge Design', 'edges', 11, '["\\bhidden fore.?edge\\b", "\\bfore.?edge artwork\\b", "\\bforedge artwork\\b", "\\bhidden visual\\b", "\\billustrated foreedge\\b", "\\bhidden illustration\\b", "\\bfore-edge illustration\\b", "\\bhidden fore.edge artwork\\b", "\\bstencilled? fore.?edge\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('7f3853dc-0d54-4e59-8317-2c50fd7cb6d0', 'continuous_edge_design', 'Continuous/Series Edge Design', 'edges', 12, '["\\bcontinuous edge\\b", "\\bseries connected edges\\b", "\\bline up with the first book\\b", "\\bline up with the first two\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('e856fed7-8380-4ec6-b220-9aec70791f31', 'redesigned_cover', 'Redesigned Cover', 'cover', 13, '["\\bredesigned covers?\\b", "\\bexclusive covers?\\b", "\\bexclusive redesigned\\b", "\\bfully redesigned covers?\\b", "\\bcover redesign\\b", "\\bexclusive new covers?\\b", "\\bcover art\\b", "\\bcase cover art\\b", "\\bexclusive illustrated hardcover\\b", "\\bexclusive hardcover illustration\\b", "\\bhardcover illustration\\b", "\\billustrated hardcover\\b", "\\bprinted hardcover case\\b", "\\bhardcover case art\\b", "\\bexclusive cover illustrated\\b", "\\bexclusive re.designed covers?\\b", "\\bcover variant\\b", "\\bexclusive cover variant\\b", "\\bexclusive illustrated case\\b", "\\bexclusive case illustration\\b", "\\bexclusive cover change\\b", "\\bcover design\\b", "\\boverall cover design\\b", "\\boverall book design\\b", "\\boverall jacket design\\b", "\\bthe hardcov\\w+ design\\b", "\\bexclusive case design\\b", "\\bexclusive\\s+cover\\s+design\\b", "\\boverall design\\b"]'::jsonb, '["\\boriginal\\b", "\\btrade cover\\b", "\\bfrom the publisher\\b", "\\bUK trade\\b"]'::jsonb, true, NOW(), NOW()),
    ('8d7c4aa3-f562-4323-9198-7b73ef9ac5cf', 'original_cover', 'Original/Trade Cover', 'cover', 14, '["\\boriginal cover\\b", "\\boriginal covers\\b", "\\btrade cover\\b", "\\bfrom the publisher\\b", "\\bUK trade cover\\b", "\\boriginal trade cover\\b", "\\bpublisher.{0,5}cover\\b", "\\boriginal.{3,30}covers?\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('87ea2291-eb69-493a-81f5-a4ad429b6f8d', 'cover_recolour', 'Cover Recolour', 'cover', 15, '["\\bcover recolour\\b", "\\bcover re.colour\\b", "\\brecoloured cover\\b", "\\brecoloured jacket\\b", "\\bcolourway.{0,10}cover\\b", "\\bexclusive recolour jacket\\b", "\\bcolourway change\\b", "\\bbespoke re.colour cover\\b", "\\bbespoke re.colour jacket\\b", "\\bexclusive colourway cover\\b", "\\bexclusive colourway\\b", "\\bcolourway cover variant\\b", "\\bbespoke exclusive re.colour cover\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('7020efd6-0128-48f5-8662-f242592a4bac', 'dust_jacket', 'Dust Jacket', 'cover', 16, '["\\bdust jackets?\\b", "\\bdustjackets?\\b", "\\bjacket design\\b", "\\boverall jacket design\\b", "\\bwraparound cover\\b", "\\bexclusive redesigned jackets?\\b", "\\bjacket illustration\\b", "\\badd.on dust jackets?\\b", "\\balternative dust jacket\\b", "\\balternate dust jacket\\b", "\\bcomplete redesigned jacket\\b", "\\bbespoke jacket exclusive\\b", "\\bbespoke jacket\\b", "\\bjacket arts?\\b", "\\bjacket with a colourway\\b", "\\bexclusive jacket\\b", "\\bredesigned jacket\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('e711131f-8af1-468a-9868-448c350da0ba', 'reversible_dust_jacket', 'Reversible Dust Jacket', 'cover', 17, '["\\breversible dust jacket\\b", "\\breversible dustjacket\\b", "\\breverse dust jacket\\b", "\\breverse of the dust jacket\\b", "\\bREVERSIBLE DUST JACKET\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('4dd673aa-eaa8-4238-b833-29c2103097a4', 'reversible_dust_jacket_colourway', 'Reversible DJ — Colourway of Trade Cover', 'cover', 18, '["\\bcolou?r variation of the trade cover\\b", "\\bcolou?rway variation of the trade cover\\b", "\\bcolou?rway variation of the trade\\b", "\\bcolou?r variant of the trade cover\\b", "\\bcolou?rway of the trade cover\\b", "\\btext colou?r variation of the trade\\b", "\\btext colou?rway variation of the trade\\b", "\\balternative colou?r.way of the trade cover\\b", "\\bshade variation of the trade cover\\b", "\\bfeaturing the trade cover\\b", "\\balternative text colou?r\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('303e04d5-ea67-46d4-ae6e-d51508f47d20', 'uv_spot', 'UV Spot / Gloss', 'cover', 19, '["\\buv spot\\b", "\\bspot uv\\b", "\\bspot gloss\\b", "\\bspot.?glossed\\b", "\\bhigh.?gloss\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('31eb3608-77aa-450a-a311-4e8c151a8f18', 'die_cut', 'Die Cut', 'cover', 20, '["\\bdie cut\\b", "\\bdiecut\\b", "\\bcut out.{0,5}front cover\\b", "\\bcut out.{0,5}cover\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('279531c4-0067-4841-8eea-0f8185029097', 'cover_typography', 'Cover Typography', 'cover', 21, '["\\bcover typography\\b", "\\btypography.{0,5}cover\\b", "\\btypography\\b", "\\bcustom typography\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('385dd006-1090-416e-a224-5c421fbe34de', 'foil', 'Foil', 'cover', 22, '["\\bfoil\\b", "\\bfoiling\\b", "\\bfoiled\\b", "\\bembossing\\b", "\\bembossed\\b"]'::jsonb, '["\\bgilded edges\\b", "\\bfoiled edges\\b", "\\bholographic edges\\b"]'::jsonb, true, NOW(), NOW()),
    ('2976a4fb-7ff4-4181-96e3-602fa6581962', 'endpapers', 'Endpapers', 'interior', 23, '["\\bendpapers?\\b", "\\bend paper\\b", "\\bend papers\\b", "\\bend pages?\\b", "\\bendpages\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('80a7d582-77f1-42ea-9b3a-d00acbf40e08', 'matching_spine', 'Matching Spine', 'binding', 24, '["\\bmatching spine\\b", "\\bmatching spines\\b", "\\bnew spine design\\b", "\\bquote on the spine\\b", "\\bquotes on the spine\\b", "\\bimitation quarter.?bound spine\\b", "\\bacross all.{0,10}spines?\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('8e9ed21c-c138-4adf-a766-e346354ee67e', 'slipcase', 'Slipcase', 'binding', 25, '["\\bslipcase\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('951a250e-1cbe-4815-8a35-161a794fbe60', 'hardback', 'Hardback/Hardcover', 'format', 26, '["\\bhardback\\b", "\\bhardcover\\b", "\\bnaked hardback\\b", "\\bnaked hardcover\\b", "\\bhardcase\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('9bf968e1-71f3-4eec-ae92-f7d1d47f887d', 'paper_quality', 'Paper Quality', 'binding', 27, '["\\bFSC paper\\b", "\\bacid free\\b", "\\bMasterblank\\b", "\\bMunken\\b", "\\b100gsm\\b", "\\bgsm.{0,5}paper\\b", "\\bacid.free paper\\b", "\\bprinted on.{0,30}paper\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('3d9ba4f2-a333-4be0-ab95-01cd038908e6', 'head_tail_bands', 'Head & Tail Bands', 'binding', 28, '["\\bhead and tail bands?\\b", "\\bhead & tail bands?\\b", "\\bhead.tail bands?\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('6be2e961-253d-4f84-8936-c234ad90bfaa', 'smyth_sewn', 'Smyth Sewn Binding', 'binding', 29, '["\\bsmyth sewn\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('b57daa8a-2f53-4974-8681-2dedf6185a60', 'author_letter', 'Author Letter', 'extras', 30, '["\\bauthor letters?\\b", "\\bletter from the author\\b", "\\bbound.?in letters?\\b", "\\bbound in letters?\\b", "\\binbound letter\\b", "\\bletter written by the author\\b", "\\bbound author letters?\\b", "\\bbound-in author letters?\\b", "\\bbound in author letters?\\b", "\\bauthorletter\\b", "\\bhandwritten letter\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('0bf21ed3-3ada-469d-8cc3-1e7817ac79e2', 'overlay', 'Overlay', 'extras', 31, '["\\boverlay\\b", "\\boverlays\\b", "\\bvellum overlay\\b", "\\bbound vellum\\b", "\\bvellum bound\\b", "\\bvellum insert\\b", "\\bvelum bound\\b", "\\bbound NSFW vellum\\b", "\\bbound spicy vellum\\b", "\\bset of.{0,5}page overlays\\b", "\\bTHREE illustrated overlays\\b", "\\bFOUR illustrated overlays\\b", "\\bbound overlay\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('ddf8ff63-3258-4adb-97a2-ac4b5f855144', 'ribbon', 'Ribbon Bookmark', 'extras', 32, '["\\bribbon bookmark\\b", "\\bribbon marker\\b", "\\bribbon markers\\b", "\\bribbon bookmarks\\b", "\\bprinted ribbon\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('becdcf98-63d0-4748-9382-f3e9cb95ad19', 'sticker', 'Sticker', 'extras', 33, '["\\bstickers?\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('4c13afd8-9819-45c3-8e8b-73df8e14df98', 'art_print', 'Art Print', 'extras', 34, '["\\bart print\\b", "\\b5x7 art print\\b", "\\bspicy art print\\b", "\\bNSFW.{0,5}art print\\b", "\\bbonus art print\\b", "\\bSPICY.{0,5}art print\\b", "\\bSPICY 5x7\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('cc7791fb-f926-4e3a-86f0-ec1c7f78f6ca', 'bookmark', 'Bookmark (non-ribbon)', 'extras', 35, '["\\bbookmark\\b"]'::jsonb, '["\\bribbon bookmark\\b"]'::jsonb, true, NOW(), NOW()),
    ('271d31ae-3a8a-4282-9d76-28d6a4484976', 'bonus_content', 'Bonus Content', 'extras', 36, '["\\bbonus content\\b", "\\bbonus chapters?\\b", "\\bbonus scenes?\\b", "\\bbonus material\\b", "\\bexclusive bonus\\b", "\\bbonus epilogue\\b", "\\bdeleted scenes?\\b", "\\bshort story\\b", "\\bexclusive deleted\\b", "\\bexclusive scenes?\\b", "\\bexclusive extended edition\\b", "\\bbonus reading material\\b", "\\bexclusive bonus chapter\\b", "\\bforeword from the author\\b", "\\bnote from the author\\b", "\\bletter written by the author\\b", "\\bPOV bonus\\b", "\\bbonus POV\\b", "\\bbound.?in bonus materials?\\b", "\\bfirst chapter of\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('8bd4112f-4ce0-449b-ab91-a90ceab5a085', 'numbered', 'Numbered', 'extras', 37, '["\\bnumbered\\b", "\\beach copy will be numbered\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('3e41b8b7-5e45-4240-99a1-108ff198f682', 'limited', 'Limited Edition', 'extras', 38, '["\\blimited edition\\b", "\\blimited\\b", "\\b\\d[,\\d]+ copies\\b"]'::jsonb, '["\\bnumbered\\b"]'::jsonb, true, NOW(), NOW()),
    ('9d72fa96-b921-4caa-8de5-f9abc4e27979', 'proofreading', 'Proofreading', 'extras', 39, '["\\bproofreading\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('dd754bef-7edf-4158-8200-24e1e737472e', 'interior_art', 'Interior Art', 'interior', 40, '["\\binterior art\\b", "\\bcharacter arts?\\b", "\\bcharacter artwork\\b", "\\bcharacter illustration\\b", "\\bchapter header art\\b", "\\bchapter headers\\b", "\\bmap artwork\\b", "\\bmap art\\b", "\\bfull colou?r arts?\\b", "\\bfull colou?r artwork\\b", "\\billustrated pages\\b", "\\billustrations\\b", "\\billustration\\b", "\\btipped.?in artwork\\b", "\\bexclusive tip in page design\\b", "\\billustrator\\b", "\\bfull art\\b"]'::jsonb, '["\\bhidden illustration\\b", "\\bon the hardcover\\b", "\\bon the hardback\\b"]'::jsonb, true, NOW(), NOW()),
    ('928f3660-e2db-4ed1-ad1b-105de8c73c86', 'interior_formatting', 'Interior Formatting', 'interior', 41, '["\\binterior formatting\\b", "\\bformatting\\b", "\\bchapter header\\b", "\\btwo.colour printing\\b", "\\bfull colour printing\\b", "\\btwo.colored printing\\b"]'::jsonb, '["\\bon the hardback\\b"]'::jsonb, true, NOW(), NOW()),
    ('a3189fbb-57c5-414e-bea5-10c93c89ecc6', 'format_b', 'B Format', 'format', 42, '["\\bB[\\-\\s]?\\s*format\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('1a86641a-2fd3-4145-b80c-dc12564515de', 'format_royal', 'Royal Format', 'format', 43, '["\\broyal format\\b", "\\broyal hardback\\b", "\\broyal size\\b", "\\broyal hardbacks\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('a43be3e2-6a38-485c-b883-687b21668dcb', 'format_demy', 'Demy Format', 'format', 44, '["\\bdemy\\b", "\\bbook size\\b", "5\\s*[\u215c\u215d].{0,5}[x\u00d7]\\s*8\\s*[\u00bc\u00bd]"]'::jsonb, '[]'::jsonb, true, NOW(), NOW()),
    ('33d77f0d-194d-43ad-a728-821a568c95f6', 'paperback', 'Paperback', 'format', 45, '["\\bpaperback\\b"]'::jsonb, '[]'::jsonb, true, NOW(), NOW());
  END IF;
END $$;
